export * from './AccountrestcontrollerApi';
import { AccountrestcontrollerApi } from './AccountrestcontrollerApi';
export * from './AuthenticationcontrollerApi';
import { AuthenticationcontrollerApi } from './AuthenticationcontrollerApi';
export * from './CommentsrestcontrollerApi';
import { CommentsrestcontrollerApi } from './CommentsrestcontrollerApi';
export * from './DoodlerestcontrollerApi';
import { DoodlerestcontrollerApi } from './DoodlerestcontrollerApi';
export * from './ErrorrestcontrollerApi';
import { ErrorrestcontrollerApi } from './ErrorrestcontrollerApi';
export * from './MatchesrestcontrollerApi';
import { MatchesrestcontrollerApi } from './MatchesrestcontrollerApi';
export * from './NewsrestcontrollerApi';
import { NewsrestcontrollerApi } from './NewsrestcontrollerApi';
export * from './PasswordrecoveryrestcontrollerApi';
import { PasswordrecoveryrestcontrollerApi } from './PasswordrecoveryrestcontrollerApi';
export * from './PollrestcontrollerApi';
import { PollrestcontrollerApi } from './PollrestcontrollerApi';
export * from './RegistrationrestcontrollerApi';
import { RegistrationrestcontrollerApi } from './RegistrationrestcontrollerApi';
export * from './SeasonsrestcontrollerApi';
import { SeasonsrestcontrollerApi } from './SeasonsrestcontrollerApi';
export * from './TeamsrestcontrollerApi';
import { TeamsrestcontrollerApi } from './TeamsrestcontrollerApi';
export const APIS = [AccountrestcontrollerApi, AuthenticationcontrollerApi, CommentsrestcontrollerApi, DoodlerestcontrollerApi, ErrorrestcontrollerApi, MatchesrestcontrollerApi, NewsrestcontrollerApi, PasswordrecoveryrestcontrollerApi, PollrestcontrollerApi, RegistrationrestcontrollerApi, SeasonsrestcontrollerApi, TeamsrestcontrollerApi];
