/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PasswordrecoveryrestcontrollerApi {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * 
     * @summary Get a password recovery code
     * @param passwordRecoveryDTO passwordRecoveryDTO
     */
    public forgotPassword(passwordRecoveryDTO: models.PasswordRecoveryDTO, extraHttpRequestParams?: any): Observable<models.ResponseEntity> {
        return this.forgotPasswordWithHttpInfo(passwordRecoveryDTO, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Set a new password using recovery code
     * @param passwordRecoveryDTO passwordRecoveryDTO
     */
    public useRecoveryCode(passwordRecoveryDTO: models.PasswordRecoveryDTO, extraHttpRequestParams?: any): Observable<models.ResponseEntity> {
        return this.useRecoveryCodeWithHttpInfo(passwordRecoveryDTO, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * Get a password recovery code
     * 
     * @param passwordRecoveryDTO passwordRecoveryDTO
     */
    public forgotPasswordWithHttpInfo(passwordRecoveryDTO: models.PasswordRecoveryDTO, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/v1/accounts/password/recovery';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'passwordRecoveryDTO' is not null or undefined
        if (passwordRecoveryDTO === null || passwordRecoveryDTO === undefined) {
            throw new Error('Required parameter passwordRecoveryDTO was null or undefined when calling forgotPassword.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: passwordRecoveryDTO == null ? '' : JSON.stringify(passwordRecoveryDTO), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Set a new password using recovery code
     * 
     * @param passwordRecoveryDTO passwordRecoveryDTO
     */
    public useRecoveryCodeWithHttpInfo(passwordRecoveryDTO: models.PasswordRecoveryDTO, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/v1/accounts/password/recovery';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'passwordRecoveryDTO' is not null or undefined
        if (passwordRecoveryDTO === null || passwordRecoveryDTO === undefined) {
            throw new Error('Required parameter passwordRecoveryDTO was null or undefined when calling useRecoveryCode.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: passwordRecoveryDTO == null ? '' : JSON.stringify(passwordRecoveryDTO), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
