/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RegistrationrestcontrollerApi {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * 
     * @summary Create an account
     * @param registrationDTO registrationDTO
     * @param captchaResponse captchaResponse
     */
    public createAccount(registrationDTO: models.RegistrationDTO, captchaResponse: string, extraHttpRequestParams?: any): Observable<models.ResponseEntity> {
        return this.createAccountWithHttpInfo(registrationDTO, captchaResponse, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * Create an account
     * 
     * @param registrationDTO registrationDTO
     * @param captchaResponse captchaResponse
     */
    public createAccountWithHttpInfo(registrationDTO: models.RegistrationDTO, captchaResponse: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/api/v1/registration';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'registrationDTO' is not null or undefined
        if (registrationDTO === null || registrationDTO === undefined) {
            throw new Error('Required parameter registrationDTO was null or undefined when calling createAccount.');
        }
        // verify required parameter 'captchaResponse' is not null or undefined
        if (captchaResponse === null || captchaResponse === undefined) {
            throw new Error('Required parameter captchaResponse was null or undefined when calling createAccount.');
        }
        if (captchaResponse !== undefined) {
            queryParameters.set('captchaResponse', <any>captchaResponse);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: registrationDTO == null ? '' : JSON.stringify(registrationDTO), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
