/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import * as models from "./models";

export interface MatchDTO {
    /**
     * Goals scored by awayteam
     */
    atGoals?: string;

    /**
     * Name of the awayteam
     */
    awayTeam?: string;

    /**
     * Date when match will be played, formatted dd/mm/YYYY
     */
    date?: string;

    fullAddress?: string;

    /**
     * Goals of this match, orederd
     */
    goals?: Array<models.GoalDTO>;

    /**
     * Match doodle
     */
    hasDoodle?: boolean;

    /**
     * Name of the hometeam
     */
    homeTeam?: string;

    /**
     * Hour when match will be played, formatted HH:mm
     */
    hour?: string;

    /**
     * Goals scored by hometeam
     */
    htGoals?: string;

    id?: number;

    /**
     * Match location
     */
    locationUrl?: string;

    /**
     * Motm poll
     */
    poll?: models.MatchPollDTO;

    /**
     * Match status
     */
    status?: string;

}
