version: 2.1

var_1: &job_defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.20.0

workflows:
  version: 2
  build:
    jobs:
      - build_and_release

jobs:
  "build_and_release":
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm@8.19.4
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm -v && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: install-angular
          command: npm install -g -dd @angular/cli
      - run:
          name: build-angular
          environment:
            BRANCH: <<pipeline.git.branch>>
          command: |
            if [ "${BRANCH}" == "master" ]; then
              ng build --aot --configuration=p
            else
              ng build --aot --configuration=q
            fi
      - run:
          name: install-firebase-tools
          command: npm install -g -dd firebase-tools # installs firebase to run firebase deploy
      - run:
          name: deploy-to-firebase
          environment:
            BRANCH: <<pipeline.git.branch>>
          command: |
            if [ "${BRANCH}" == "master" ]; then
              firebase deploy --project=svk-p-01 --only hosting --non-interactive --token $FIREBASE_TOKEN
            else
              firebase deploy --project=svk-q-01 --only hosting --non-interactive --token $FIREBASE_TOKEN
            fi
