version: 2.1

var_1: &job_defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.19.0

workflows:
  version: 2
  build:
    jobs:
      - build_and_release

jobs:
  "build_and_release":
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: install-angular
          command: npm install -g -dd @angular/cli
      - run:
          name: build-production
          command: ng build --aot --prod --configuration=p
          filters:
            branches:
              only:
                - master
      - run:
          name: build-quality
          command: ng build --aot --prod --configuration=q
          filters:
            branches:
              ignore:
                - master
      - run:
          name: install-firebase-tools
          command: npm install -g -dd firebase-tools # installs firebase to run firebase deploy
      - run:
          name: deploy-production
          command: firebase deploy --project=svk-p-01 --only hosting --token $FIREBASE_TOKEN --non-interactive
          filters:
            branches:
              only:
                - master
      - run:
          name: deploy-quality
          command: firebase deploy --project=svk-q-01 --only hosting --token $FIREBASE_TOKEN --non-interactive
          filters:
            branches:
              ignore:
                - master
