version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - install
      - build-q:
          requires:
            - install
          filters:
            branches:
              not:
                - master
      - release-q:
          requires:
            - build-q
          filters:
            branches:
              not:
                - master
      - build-p:
          requires:
            - install
          filters:
            branches:
              only:
                - master
      - release-p:
          requires:
            - build-p
          filters:
            branches:
              only:
                - master

jobs:
  "install":
    docker:
      - image: cimg/node:16.19.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  "build-prod":
    steps:
      - run:
          name: install-amgular
          command: npm install -g -dd @angular/cli
      - run: ng build --aot --prod --configuration=p
  "build-q":
    steps:
      - run:
          name: install-amgular
          command: npm install -g -dd @angular/cli
      - run: ng build --aot --prod --configuration=q
  "release-p":
    steps:
      - run:
          name: install-firebase
          command: npm install -g -dd firebase-tools # installs firebase to run firebase deploy
      - run: firebase deploy --project=svk-p-01 --only hosting --token $FIREBASE_TOKEN --non-interactive
  "release-q":
    steps:
      - run:
          name: install-firebase
          command: npm install -g -dd firebase-tools # installs firebase to run firebase deploy
      - run: firebase deploy --project=svk-q-01 --only hosting --token $FIREBASE_TOKEN --non-interactive
