version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - install
      - build
      - release

jobs:
  install:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.19.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  build:
    steps:
      - run:
          name: install-amgular
          command: npm install -g -dd @angular/cli
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run: ng build --aot --prod --configuration=p
      - when:
          condition:
            not: [ master, << pipeline.git.branch >> ]
          steps:
            - run: ng build --aot --prod --configuration=q
  release:
    steps:
      - run:
          name: install-firebase
          command: npm install -g -dd firebase-tools # installs firebase to run firebase deploy
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run: firebase deploy --project=svk-p-01 --only hosting --token $FIREBASE_TOKEN --non-interactive
      - when:
          condition:
            not: [ master, << pipeline.git.branch >> ]
          steps:
            - run: firebase deploy --project=svk-q-01 --only hosting --token $FIREBASE_TOKEN --non-interactive