/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AccountDTO} from './accountDTO';
import {VotesDTO} from './votesDTO';


export interface MatchPollDTO {
    id?: string;
    matchDate?: string;
    matchDescription?: string;
    matchId?: string;
    options?: Array<AccountDTO>;
    status?: string;
    totalVotes?: number;
    votes?: Array<VotesDTO>;
}
