/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AccountDTO} from './accountDTO';


export interface PresenceDTO {
    account?: AccountDTO;
    editable?: boolean;
    modified?: string;
    type?: PresenceDTO.TypeEnum;
}
export namespace PresenceDTO {
    export type TypeEnum = 'NOT_PRESENT' | 'PRESENT' | 'NOT_FILLED_IN' | 'ANONYMOUS' | 'RESERVE';
    export const TypeEnum = {
        NOTPRESENT: 'NOT_PRESENT' as TypeEnum,
        PRESENT: 'PRESENT' as TypeEnum,
        NOTFILLEDIN: 'NOT_FILLED_IN' as TypeEnum,
        ANONYMOUS: 'ANONYMOUS' as TypeEnum,
        RESERVE: 'RESERVE' as TypeEnum
    }
}
