// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'title.error.unknown': 'Unknown error',
    'text.error.unknown': 'Epic fail. Open goal, but the webmaster somehow missed it. Or the internet broke again.',
    'text.search': 'Search',
    'text.registration.succes': 'The registration was successful.</br>Your account will have to be activated by the administrator. You will be notified of this action.</br>Afterwards, you can try to login.</br></br>Have a lot of fun on this website!',
    'text.recovery.request.email.failed' : 'Could not send email, please try again later.',
    'text.recovery.request.success' : 'An email with the recovery code has been sent. Please check your inbox.',
    'hello world': 'hello world',
    'nav.messages': 'Messages',
    'nav.login' : 'Login',
    'nav.home' : 'Home',
    'nav.about': 'About us',
    'nav.faq': 'Website FAQ',
    'nav.matches': 'matches',
    'nav.manOfTheMatch': 'Man of the match',
    'nav.teams': 'Teams',
    'nav.team': 'Our team',
    'nav.doodle': 'Doodles',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.contact': 'Contact',
    'nav.register': 'Register',
    'nav.recovery.request' : 'Forgot password',
    'nav.messages.create': 'Create a message',
    'label.recovery.email' : 'Email',
    'label.username' : 'Email address',
    'label.password' : 'Password',
    'label.match.time': 'Time',
    'label.match.date': 'Date',
    'label.match.awayTeam': 'Away team',
    'label.match.homeTeam': 'Home team',
    'label.match.season': 'Season',
    'label.rememberMe': 'Stay logged in',
    'label.message.sendAndPost': 'Send message to active members and post on this website',
    'label.message.sendOnly': 'Send to active members',
    'label.message.postOnly': 'Post only on this website, do not send to active members',
    'label.message.content': 'Message',
    'label.message.title': 'Title',
    'label.registration.password': 'Password',
    'label.registration.repeatPassword': 'Type the password again',
    'label.registration.firstName': 'First name',
    'label.registration.lastName': 'Last name',
    'label.registration.email': 'Email',
    'btn.login': 'Login',
    'btn.reactions': 'Reactions',
    'btn.submit': 'Submit',
    'btn.cancel': 'Cancel',
    'text.match.next': 'Next match',
    'validation.username.required': "Email is required",
    'validation.password.required': "Password is required",
    'validation.email.email': "Please specify a valid email address",
    'validation.required': "This field cannot be empty",
    'validation.password.pattern': "Please use 5 to 15 characters for the password. Allowed characters: letters, digits, dots, underscores and dashes",
    'validation.firstName.pattern': 'The name contains invalid characters (do not use abbreviations, dots or other characters)',
    'validation.lastName.pattern': 'The name contains invalid characters (do not use abbreviations, dots or other characters)',
    'validation.atGoals.pattern': 'Only digits are allowed',
    'validation.htGoals.pattern': 'Only digits are allowed',
    'validation.repeatPassword.equals': 'The two passwords should match'
};