// lang-en.ts

export const LANG_NL_NAME = 'nl';

export const LANG_NL_TRANS = {
    'title.error.unknown': 'Onbekende fout',
    'text.error.unknown': 'Epic fail. Een open doel, maar de webmaster heeft onbegrijpelijk gemist. Of het internet is weer eens kapot.',
    'text.search': 'Zoeken',
    'hello world': 'hello world',
    'nav.messages': 'Berichten',
    'nav.login' : 'Inloggen',
    'nav.home' : 'Home',
    'nav.about': 'Over ons',
    'nav.faq': 'Website FAQ',
    'nav.matches': 'Matchen',
    'nav.manOfTheMatch': 'Man van de match',
    'nav.teams': 'Teams',
    'nav.team': 'Ons team',
    'nav.doodle': 'Doodles',
    'nav.profile': 'Profiel',
    'nav.logout': 'Uitloggen',
    'nav.contact': 'Contact',
    'nav.messages.create': 'Maak een bericht aan',
    'label.username' : 'Email adres',
    'label.password' : 'Wachtwoord',
    'label.match.time': 'Tijdstip',
    'label.match.date': 'Datum',
    'label.match.awayTeam': 'Uitploeg',
    'label.match.homeTeam': 'ThuisPloeg',
    'label.match.season': 'Seizoen',
    'label.rememberMe': 'Ingelogd blijven',
    'label.message.sendAndPost': 'Stuur dit bericht naar actieve leden en post op deze website',
    'label.message.sendOnly': 'Stuur dit bericht naar alle actieve leden',
    'label.message.postOnly': 'Post alleen op deze website, verstuur niet naar de leden',
    'label.message.content': 'Bericht',
    'label.message.title': 'Titel',
    'label.registration.password': 'Wachtwoord',
    'label.registration.repeatPassword': 'Typ het wachtwoord opnieuw',
    'label.registration.firstName': 'Voornaam',
    'label.registration.lastName': 'Familienaam',
    'label.registration.email': 'E-mail',
    'btn.login': 'Inloggen',
    'btn.reactions': 'Reacties',
    'btn.submit': 'Verzenden',
    'btn.cancel': 'Annuleren',
    'text.match.next': 'Volgende match'
};