// lang-en.ts

export const LANG_NL_NAME = 'nl';

export const LANG_NL_TRANS = {
    'title.error.unknown': 'Onbekende fout',
    'title.service.unavailable': "Service down",
    'text.error.unknown': 'Epic fail. Een open doel, maar de webmaster heeft onbegrijpelijk gemist. Of het internet is weer eens kapot.',
    'text.search': 'Zoeken',
    'text.teams.empty': 'Geen teams gevonden.',
    'text.seasons.empty': 'Geen matchen gevonden.',
    'text.matches.empty': 'Geen matchen gevonden voor dit seizoen.',
    'text.doodles.empty': 'Geen doodles gevonden.',
    'text.motm.empty': 'Geen \"Man van de match\" polls gevonden.',
    'text.registration.succes': 'De registratie is gelukt.</br>Uw account zal nu geactiveerd moeten worden door de beheerder. U wordt op de hoogte gebracht van deze actie.</br>Daarna kan u rechts boven inloggen.</br></br>Veel plezier op deze website!',
    'text.recovery.request.email.failed' : 'De email kon niet verstuurd worden. Gelieve later opnieuw te proberen.',
    'text.recovery.request.success' : 'Er werd een email verzonden met de wachtwoord reset code. Gelieve je inbox te raadplegen.',
    'text.service.unavailable': "De server is momenteel down wegens onderhoud. Gelieve later opnieuw te proberen.",
    'hello world': 'hello world',
    'nav.messages': 'Berichten',
    'nav.login' : 'Inloggen',
    'nav.home' : 'Home',
    'nav.about': 'Over ons',
    'nav.faq': 'Website FAQ',
    'nav.matches': 'Matchen',
    'nav.manOfTheMatch': 'Man van de match',
    'nav.teams': 'Teams',
    'nav.team': 'Ons team',
    'nav.doodle': 'Doodles',
    'nav.profile': 'Profiel',
    'nav.logout': 'Uitloggen',
    'nav.contact': 'Contact',
    'nav.register': 'Registreer',
    'nav.messages.create': 'Maak een bericht aan',
    'nav.recovery.request' : 'Wachtwoord vergeten',
    'label.recovery.email' : 'Email',
    'label.username' : 'Email adres',
    'label.password' : 'Wachtwoord',
    'label.match.time': 'Tijdstip',
    'label.match.date': 'Datum',
    'label.match.awayTeam': 'Uitploeg',
    'label.match.homeTeam': 'ThuisPloeg',
    'label.match.season': 'Seizoen',
    'label.rememberMe': 'Ingelogd blijven',
    'label.message.sendAndPost': 'Stuur dit bericht naar actieve leden en post op deze website',
    'label.message.sendOnly': 'Stuur dit bericht naar alle actieve leden',
    'label.message.postOnly': 'Post alleen op deze website, verstuur niet naar de leden',
    'label.message.content': 'Bericht',
    'label.message.title': 'Titel',
    'label.registration.password': 'Wachtwoord',
    'label.registration.repeatPassword': 'Typ het wachtwoord opnieuw',
    'label.registration.firstName': 'Voornaam',
    'label.registration.lastName': 'Familienaam',
    'label.registration.email': 'E-mail',
    'btn.login': 'Inloggen',
    'btn.reactions': 'Reacties',
    'btn.submit': 'Verzenden',
    'btn.cancel': 'Annuleren',
    'text.match.next': 'Volgende match',
    'validation.username.required': "Email adres is vereist",
    'validation.password.required': "Wachtwoord is vereist",
    'validation.email.email': "Gelieve een correct email adres op te geven",
    'validation.required': "Mag niet leeg zijn",
    'validation.password.pattern': "Minimaal 5 tekens, maximaal 15. Toegelaten karakters: letters, cijfers, punten, dashes en underscores",
    'validation.firstName.pattern': 'De naam bevat niet toegelaten karakters (gebruik geen afkortingen, punten of vreemde tekens)',
    'validation.lastName.pattern': 'De naam bevat niet toegelaten karakters (gebruik geen afkortingen, punten of vreemde tekens)',
    'validation.atGoals.pattern': 'Alleen cijfers zijn toegelaten',
    'validation.htGoals.pattern': 'Alleen cijfers zijn toegelaten',
    'validation.repeatPassword.equals': 'De wachtwoorden moeten hetzelfde zijn'
};