// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'title.account.details': 'profile',
    'title.account.password': 'Change password',
    'title.error.unknown': 'Unknown error',
    'title.season': 'Season',
    'title.service.unavailable': "Server unavailable",
    'title.error.404': 'Pagina niet gevonden',
    'text.error.unknown': 'Epic fail. Open goal, but the webmaster somehow missed it. Or the internet broke again.',
    'text.search': 'Search',
    'text.teams.empty': 'No teams found.',
    'text.seasons.empty': 'No matches found.',
    'text.matches.empty': 'No matches for season found.',
    'text.doodles.empty': 'No doodles found.',
    'text.motm.empty': 'No \"Man of the match\" polls found.',
    'text.registration.succes': 'The registration was successful.</br>Your account will have to be activated by the administrator. You will be notified of this action.</br>Afterwards, you can try to login.</br></br>Have a lot of fun on this website!',
    'text.recovery.request.email.failed' : 'Could not send email, please try again later.',
    'text.recovery.request.success' : 'An email with the recovery code has been sent. Please check your inbox.',
    'text.service.unavailable': "The server is temporarily down. Please try again later.",
    'text.match.status.notPlayed': 'Not yet played',
    'text.match.status.played': 'Played',
    'text.match.status.cancelled': 'Cancelled',
    'text.match.scorer' : 'Goalscorer',
    'text.match.assist' : 'Assist',
    'text.match.ownGoal': 'Owngoal',
    'text.statistics.assists': 'A',
    'text.statistics.goals': 'G',
    'text.statistics.played': 'P',
    'text.name': 'Name',
    'text.match.create.success': 'The match was successfully created.',
    'text.password.success.change': 'Password successfully changed.',
    'text.account.success.change': 'Account successfully updated.',
    'text.polls.no.votes' : 'No votes yet',
    'text.goalKeeper': 'Goalkeeper',
    'text.defender': 'Defender',
    'text.midfielder': 'Midfielder',
    'text.forward': 'Forward',
    'text.goalKeepers': 'Goalkeepers',
    'text.defenders': 'Defenders',
    'text.midfielders': 'Midfielders',
    'text.forwards': 'Forwards',
    'text.unknown': 'Unknown',
    'text.on': 'on',
    'text.by': 'by',
    'text.yes': 'yes',
    'text.no': 'no',
    'text.no.votes': 'No one voted yet.',
    'text.verification.delete.news': 'Are you sure you want to delete this message?',
    'text.verification.delete.match': 'Delete match?',
    'text.team.success.create': 'The team was succesfully created',
    'text.votes': 'Vote(s)',
    'text.vote': 'Vote',
    'text.show.more': 'Show more',
    'text.show.less': 'Show less',
    'text.verification.refresh.poll': 'Are you sure you want to refresh the poll?',
    'text.verification.reset.poll': 'Are you sure you want to reset all votes for this poll?',
    'text.motmPoll.select.player': 'Select player',
    'text.go.home': 'Go to homepage',
    'text.profile.image.unavailable': 'No image',
    'text.account.activation.not.sent': 'The account was activated, but the email was not sent.',
    'text.account.already.activated': 'This account has already been activated.',
    'text.account.success.activation': 'The account has succesfully been activated.',
    'text.error': 'Error',
    'text.error.404': 'After days of searching, the page was not found. I hope someone will find it.',
    'text.accounts.activate': 'Activate the account. You can choose to notify the user of this action. ',
    'text.doodle.hide.dates': 'Hide dates',
    'text.doodle.show.dates': 'Show dates',
    'text.doodle.modified': 'Changed on',
    'title.faq': 'Frequently asked questions',
    'text.faq': 'How does this site work?',
    'title.faq1': 'I\'m a new member, what should I do?',
    'text.faq1': 'First of all: welcome! To gain access to the restricted pages of the website, you have to <a href="/register">register</a>. After registration, the administrator can activate your account and give you access. When this is done, you can log in and you will have access.',
    'title.faq2': 'I forgot my password, what should I do?',
    'text.faq2': 'Do not panic! You can reset your password by <a href="/password/recovery/request">requesting a password reset code</a>. Fill in your email address you used to register and you will receive an email with a code (this code is valid for 1 day!) to reset your password.<br/>If you have forgotten your email address: send an email to the administrator.',
    'title.faq3': 'What on earth is the diference between the doodle and the traingsingsdoodle?',
    'text.faq3': 'The trainingsdoodle is a doodle used for... training. The reason we use a second doodle is because only registered members can use the doodle on this website! The trainingsdoodle is open for <i>everyone</i>: handy for new players who want to become a member!',
    'title.faq4': 'What if I have other questions?',
    'text.faq4': 'Then you should definitely contact the administrator!',
    'label.match.atGoals': 'Goals away team',
    'label.match.htGoals': 'Goals hometeam',
    'label.match.goals': 'Goals',
    'text.select' : 'Select',
    'hello world': 'hello world',
    'nav.messages': 'Messages',
    'nav.login' : 'Login',
    'nav.home' : 'Home',
    'nav.about': 'About us',
    'nav.faq': 'Website FAQ',
    'nav.matches': 'matches',
    'nav.statistics': 'Statistics',
    'nav.manOfTheMatch': 'Man of the match',
    'nav.teams': 'Teams',
    'nav.team': 'Our team',
    'nav.doodle': 'Doodle',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.contact': 'Contact',
    'nav.register': 'Register',
    'nav.recovery.request' : 'Forgot password',
    'nav.messages.create': 'Create a message',
    'nav.match.edit': 'Edit match',
    'nav.match.create': 'Create match',
    'nav.motm': 'Man of the match',
    'nav.accounts': 'Accounts',
    'nav.accounts.activate': 'Activate account',
    'nav.recovery.use': 'Use password reset code',
    'label.position': 'Position',
    'label.recovery.email' : 'Email',
    'label.username' : 'Email address',
    'label.match.time': 'Time',
    'label.match.date': 'Date',
    'label.match.awayTeam': 'Away team',
    'label.match.homeTeam': 'Home team',
    'label.match.season': 'Season',
    'label.rememberMe': 'Stay logged in',
    'label.message.sendAndPost': 'Send message to active members and post on this website',
    'label.message.sendOnly': 'Send to active members',
    'label.message.postOnly': 'Post only on this website, do not send to active members',
    'label.message.content': 'Message',
    'label.message.title': 'Title',
    'label.password': 'Password',
    'label.repeatPassword': 'Type the password again',
    'label.firstName': 'First name',
    'label.lastName': 'Last name',
    'label.email': 'Email',
    'label.match.status': 'Status',
    'label.city': 'City',
    'label.postalCode': 'Postal code',
    'label.address': 'Street name and number',
    'label.newPassword': 'New password',
    'label.team.name': 'Name',
    'label.team.useExistingAddress': 'Use existing address',
    'label.team.useGoogleLink': 'Use this google map',
    'label.team.address': 'List of existing addresses',
    'label.optional': 'Optional',
    'label.profile.doodleNotifications': 'Send me doodle notifications',
    'label.profile.newsNotifications': 'Send me news messages',
    'label.recovery.code': 'Password reset code',
    'label.account.sendMail': 'Send email to the user',
    'label.role': 'role',
    'label.name': 'name',
    'label.rememberUserName': 'Remember mmy email address',
    'btn.login': 'Login',
    'btn.reactions': 'Reactions',
    'btn.submit': 'Submit',
    'btn.cancel': 'Cancel',
    'btn.reset': 'Reset',
    'btn.refresh': 'Refresh',
    'text.match.next': 'Next match',
    'validation.username.required': "Email is required",
    'validation.type.required': "Please select a type",
    'validation.password.required': "Password is required",
    'validation.email.email': "Please specify a valid email address",
    'validation.required': "This field cannot be empty",
    'validation.password.pattern': "Please use 5 to 15 characters for the password. Allowed characters: letters, digits, dots, underscores and dashes",
    'validation.firstName.pattern': 'The name contains invalid characters (do not use abbreviations, dots or other characters)',
    'validation.lastName.pattern': 'The name contains invalid characters (do not use abbreviations, dots or other characters)',
    'validation.atGoals.pattern': 'Only digits are allowed',
    'validation.htGoals.pattern': 'Only digits are allowed',
    'validation.repeatPassword.equals': 'The two passwords should match',
    'validation.newPassword.pattern': 'Please use 5 to 15 characters for the password. Allowed characters: letters, digits, dots, underscores and dashes',
    'validation.postalCode.pattern': 'The postal code should only contain digits',
    'validation.username.email': 'Please specify a valid email address',
    'validation.id.matchesCurrentId': 'I don\'t think you were that good... I would pick someone else :)',
};