// lang-en.ts

export const LANG_NL_NAME = 'nl';

export const LANG_NL_TRANS = {
    'title.account.details': 'Profiel',
    'title.account.password': 'Wijzig wachtwoord',
    'title.error.unknown': 'Onbekende fout',
    'title.service.unavailable': "Service down",
    'title.season': 'Seizoen',
    'text.error.unknown': 'Epic fail. Een open doel, maar de webmaster heeft onbegrijpelijk gemist. Of het internet is weer eens kapot.',
    'text.search': 'Zoeken',
    'title.error.404': 'Pagina niet gevonden',
    'text.teams.empty': 'Geen teams gevonden.',
    'text.seasons.empty': 'Geen matchen gevonden.',
    'text.matches.empty': 'Geen matchen gevonden voor dit seizoen.',
    'text.doodles.empty': 'Geen doodles gevonden.',
    'text.motm.empty': 'Geen \"Man van de match\" polls gevonden.',
    'text.registration.succes': 'De registratie is gelukt.</br>Uw account zal nu geactiveerd moeten worden door de beheerder. U wordt op de hoogte gebracht van deze actie.</br>Daarna kan u rechts boven inloggen.</br></br>Veel plezier op deze website!',
    'text.recovery.request.email.failed' : 'De email kon niet verstuurd worden. Gelieve later opnieuw te proberen.',
    'text.recovery.request.success' : 'Er werd een email verzonden met de wachtwoord reset code. Gelieve je inbox te raadplegen.',
    'text.service.unavailable': "De server is momenteel down wegens onderhoud. Gelieve later opnieuw te proberen.",
    'text.match.status.notPlayed': 'Nog niet gespeeld',
    'text.match.status.played': 'Gespeeld',
    'text.match.status.cancelled': 'Afgelast',
    'text.match.scorer' : 'Doelpuntenmaker',
    'text.match.assist' : 'Assist',
    'text.polls.no.votes' : 'Nog geen stemmen uitgebracht',
    'text.match.ownGoal': 'Owngoal',
    'text.statistics.assists': 'Assists',
    'text.statistics.goals': 'Goals',
    'text.statistics.played': 'Gespeeld',
    'text.name': 'Naam',
    'text.match.create.success': 'De match werd succesvol aangemaakt.',
    'text.password.success.change': 'Je wachtwoord werd succesvol gewijzigd.',
    'text.account.success.change': 'Je account werd succesvol gewijzigd.',
    'text.goalKeeper': 'Doelman',
    'text.defender': 'Verdediger',
    'text.midfielder': 'Middenvelder',
    'text.forward': 'Aanvaller',
    'text.goalKeepers': 'Doelmannen',
    'text.defenders': 'Verdedigers',
    'text.midfielders': 'Middenvelders',
    'text.forwards': 'Aanvallers',
    'text.unknown': 'Onbekend',
    'text.on': 'op',
    'text.by': 'door',
    'text.yes': 'ja',
    'text.no': 'nee',
    'text.profile.image.unavailable': 'Geen afbeelding',
    'text.no.votes': 'Er werden nog geen stemmen uitgebracht.',
    'text.verification.delete.news': 'Ben je zeker dat je dit bericht wilt verwijderen?',
    'text.verification.delete.match': 'Match verwijderen?',
    'text.team.success.create': 'Het team werd succesvol aangemaakt',
    'text.votes': 'Stem(men)',
    'text.vote': 'Stem',
    'text.show.more': 'Meer tonen',
    'text.show.less': 'Minder tonen',
    'text.motmPoll.select.player': 'Selecteer speler',
    'text.verification.refresh.poll': 'Ben je zeker dat je de poll wilt vernieuwen?',
    'text.verification.reset.poll': 'Ben je zeker dat je alle stemmen wilt verwijderen?',
    'text.go.home': 'Ga naar de beginpagina',
    'text.error': 'Fout',
    'text.error.404': 'Na dagenlang zoekwerk, werd de pagina nog steeds niet gevonden. Ik hoop dat iemand ze vindt.',
    'title.faq': 'Vaak gestelde vragen',
    'text.faq': 'Hoe werkt deze website?',
    'title.faq1': 'Ik ben een nieuw lid, wat moet ik doen?',
    'text.faq1': 'Eerst en vooral: welkom! Om toegang te krijgen tot de afgeschermde delen van de website, moet je <a href="/login.html">registreren</a>. Na de registratie kan de beheerder je account activeren. Daarna kan je inloggen en heb je toegang.',
    'title.faq2': 'Ik ben mijn wachtwoord vergeten, wat nu?',
    'text.faq2': 'Vooral niet panikeren! Je kan dit rechtzetten door een wachtwoord reset code <a href="/account/getPwdRecoveryCode.html">aan te vragen</a>. Vul je email adres in waarmee je op de website geregistreerd bent en je krijgt een email met een code (let wel op: deze is slechts een dag geldig!) om je wachtwoord opnieuw in te stellen.<br/>Als je je emailadres niet meer weet: stuur dan een mailtje naar de beheerder.',
    'title.faq3': 'Wat is het verschil tussen de doodle en de traingsingsdoodle?',
    'text.faq3': 'De trainingsdoodle is de doodle die gebruikt wordt voor... trainingen. De reden hiervoor is dat alleen leden de doodle op deze website mogen aanpassen! Op de trainingsdoodle kan <i>iedereen</i> zich inschrijven: handig voor spelers die willen aansluiten!',
    'title.faq4': 'Wat als ik nog andere vragen heb?',
    'text.faq4': 'Dan mag je zeker de beheerder emailen!',
    'hello world': 'hello world',
    'nav.messages': 'Berichten',
    'nav.login' : 'Inloggen',
    'nav.home' : 'Home',
    'nav.about': 'Over ons',
    'nav.faq': 'Website FAQ',
    'nav.matches': 'Matchen',
    'nav.manOfTheMatch': 'Man van de match',
    'nav.teams': 'Teams',
    'nav.team': 'Ons team',
    'nav.doodle': 'Doodles',
    'nav.profile': 'Profiel',
    'nav.logout': 'Uitloggen',
    'nav.contact': 'Contact',
    'nav.register': 'Registreer',
    'nav.messages.create': 'Maak een bericht aan',
    'nav.recovery.request' : 'Wachtwoord vergeten',
    'nav.match.edit': 'Wijzig match',
    'nav.match.create': 'Match aanmaken',
    'nav.statistics': 'Statistieken',
    'nav.motm': 'Man van de match',
    'label.position': 'Positie',
    'nav.recovery.use': 'Gebruik wachtwoord reset code',
    'label.recovery.email' : 'Email',
    'label.username' : 'Email adres',
    'label.password' : 'Wachtwoord',
    'label.match.time': 'Tijdstip',
    'label.match.date': 'Datum',
    'label.match.awayTeam': 'Uitploeg',
    'label.match.homeTeam': 'ThuisPloeg',
    'label.match.season': 'Seizoen',
    'label.rememberMe': 'Ingelogd blijven',
    'label.message.sendAndPost': 'Stuur dit bericht naar actieve leden en post op deze website',
    'label.message.sendOnly': 'Stuur dit bericht naar alle actieve leden',
    'label.message.postOnly': 'Post alleen op deze website, verstuur niet naar de leden',
    'label.message.content': 'Bericht',
    'label.message.title': 'Titel',
    'label.repeatPassword': 'Typ het wachtwoord opnieuw',
    'label.firstName': 'Voornaam',
    'label.lastName': 'Familienaam',
    'label.email': 'E-mail',
    'label.match.status': 'Status',
    'label.match.atGoals': 'Doelpunten uitploeg',
    'label.match.htGoals': 'Doelpunten thuisploeg',
    'label.match.goals': 'Doelpunten',
    'label.city': 'Stad',
    'label.postalCode': 'Postcode',
    'label.address': 'Straatnaam en nummer',
    'label.newPassword': 'New password',
    'label.team.name': 'Naam',
    'label.team.useExistingAddress': 'Bestaand adres gebruiken',
    'label.team.useGoogleLink': 'Gebruik deze kaart',
    'label.team.address': 'Lijst van bestaande adressen',
    'label.optional': 'Optioneel',
    'label.profile.doodleNotifications': 'Stuur mij doodle notificaties',
    'label.profile.newsNotifications': 'Stuur me nieuwsberichten',
    'label.recovery.code': 'Wachtwoord reset code',
    'text.select' : 'Selecteer',
    'btn.login': 'Inloggen',
    'btn.reactions': 'Reacties',
    'btn.submit': 'Verzenden',
    'btn.cancel': 'Annuleren',
    'btn.reset': 'Resetten',
    'btn.refresh': 'Verniewen',
    'text.match.next': 'Volgende match',
    'validation.username.required': "Email adres is vereist",
    'validation.password.required': "Wachtwoord is vereist",
    'validation.email.email': "Gelieve een correct email adres op te geven",
    'validation.required': "Mag niet leeg zijn",
    'validation.password.pattern': "Minimaal 5 tekens, maximaal 15. Toegelaten karakters: letters, cijfers, punten, dashes en underscores",
    'validation.firstName.pattern': 'De naam bevat niet toegelaten karakters (gebruik geen afkortingen, punten of vreemde tekens)',
    'validation.lastName.pattern': 'De naam bevat niet toegelaten karakters (gebruik geen afkortingen, punten of vreemde tekens)',
    'validation.atGoals.pattern': 'Alleen cijfers zijn toegelaten',
    'validation.htGoals.pattern': 'Alleen cijfers zijn toegelaten',
    'validation.repeatPassword.equals': 'De wachtwoorden moeten hetzelfde zijn',
    'validation.newPassword.pattern': 'Minimaal 5 tekens, maximaal 15. Toegelaten karakters: letters, cijfers, punten, dashes en underscores',
    'validation.postalCode.pattern': 'De postcode mag alleen cijfers bevatten',
    'validation.username.email': 'Gelieve een correct email adres op te geven',
    'validation.id.matchesCurrentId': 'Zo goed was je nu ook weer niet... Ik zou toch iemand anders kiezen :)',
};