/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MatchDTO {
    address?: models.AddressDTO;

    /**
     * Goals scored by awayteam
     */
    atGoals?: number;

    /**
     * Name of the awayteam
     */
    awayTeam?: models.TeamDTO;

    /**
     * Date when match will be played, formatted dd/mm/YYYY
     */
    date?: string;

    /**
     * Goals of this match, orederd
     */
    goals?: Array<models.GoalDTO>;

    /**
     * Match doodle
     */
    hasDoodle?: boolean;

    /**
     * Name of the hometeam
     */
    homeTeam?: models.TeamDTO;

    /**
     * Hour when match will be played, formatted HH:mm
     */
    hour?: string;

    /**
     * Goals scored by hometeam
     */
    htGoals?: number;

    id?: number;

    /**
     * Match location
     */
    locationUrl?: string;

    /**
     * Motm poll
     */
    poll?: models.MatchPollDTO;

    season?: models.SeasonDTO;

    /**
     * Match status
     */
    status?: string;

    /**
     * Status text
     */
    statusText?: string;

}
