/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AddressDTO} from './addressDTO';
import {GoalDTO} from './goalDTO';
import {MatchPollDTO} from './matchPollDTO';
import {SeasonDTO} from './seasonDTO';
import {TeamDTO} from './teamDTO';


export interface MatchDTO {
    address?: AddressDTO;
    /**
     * Goals scored by awayteam
     */
    atGoals?: number;
    /**
     * Name of the awayteam
     */
    awayTeam?: TeamDTO;
    /**
     * Date when match will be played, formatted dd/mm/YYYY
     */
    date?: string;
    /**
     * Goals of this match, orederd
     */
    goals?: Array<GoalDTO>;
    /**
     * Match doodle
     */
    hasDoodle?: boolean;
    /**
     * Name of the hometeam
     */
    homeTeam?: TeamDTO;
    /**
     * Hour when match will be played, formatted HH:mm
     */
    hour?: string;
    /**
     * Goals scored by hometeam
     */
    htGoals?: number;
    id?: number;
    /**
     * Motm poll
     */
    poll?: MatchPollDTO;
    season?: SeasonDTO;
    /**
     * Match status
     */
    status?: MatchDTO.StatusEnum;
    /**
     * Status text
     */
    statusText?: string;
}
export namespace MatchDTO {
    export type StatusEnum = 'PLAYED' | 'NOT_PLAYED' | 'CANCELLED';
    export const StatusEnum = {
        PLAYED: 'PLAYED' as StatusEnum,
        NOTPLAYED: 'NOT_PLAYED' as StatusEnum,
        CANCELLED: 'CANCELLED' as StatusEnum
    }
}
