/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DoodleDTO} from './doodleDTO';


export interface MatchDoodleDTO {
    date?: string;
    description?: string;
    doodle?: DoodleDTO;
    hour?: string;
    id?: number;
    matchStatus?: MatchDoodleDTO.MatchStatusEnum;
}
export namespace MatchDoodleDTO {
    export type MatchStatusEnum = 'PLAYED' | 'NOT_PLAYED' | 'CANCELLED';
    export const MatchStatusEnum = {
        PLAYED: 'PLAYED' as MatchStatusEnum,
        NOTPLAYED: 'NOT_PLAYED' as MatchStatusEnum,
        CANCELLED: 'CANCELLED' as MatchStatusEnum
    }
}
