/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AccountDTO} from './accountDTO';
import {CommentDTO} from './commentDTO';


export interface NewsDTO {
    comments?: Array<CommentDTO>;
    content?: string;
    editable?: boolean;
    header?: string;
    id?: string;
    postDate?: string;
    postedBy?: AccountDTO;
    type?: NewsDTO.TypeEnum;
}
export namespace NewsDTO {
    export type TypeEnum = 'SEND' | 'POST' | 'POST_AND_SEND';
    export const TypeEnum = {
        SEND: 'SEND' as TypeEnum,
        POST: 'POST' as TypeEnum,
        POSTANDSEND: 'POST_AND_SEND' as TypeEnum
    }
}
