/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import * as models from "./models";

export interface PresenceDTO {
    account?: models.AccountDTO;

    editable?: boolean;

    modified?: string;

    type?: PresenceDTO.TypeEnum;

}
export namespace PresenceDTO {
    export enum TypeEnum {
        NOTPRESENT = <any> 'NOT_PRESENT',
        PRESENT = <any> 'PRESENT',
        NOTFILLEDIN = <any> 'NOT_FILLED_IN',
        ANONYMOUS = <any> 'ANONYMOUS',
        RESERVE = <any> 'RESERVE'
    }
}
