/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ProfileDTO {
    account?: models.AccountDTO;

    address?: models.AddressDTO;

    description?: string;

    id?: number;

    image?: models.ImageDTO;

    mobilePhone?: string;

    phone?: string;

    position?: ProfileDTO.PositionEnum;

}
export namespace ProfileDTO {
    export enum PositionEnum {
        GOALKEEPER = <any> 'GOALKEEPER',
        DEFENDER = <any> 'DEFENDER',
        MIDFIELDER = <any> 'MIDFIELDER',
        FORWARD = <any> 'FORWARD'
    }
}
