/**
 * Soccer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: voetbalsvk@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {URLStreamHandler} from './uRLStreamHandler';


export interface URL {
    authority?: string;
    content?: any;
    defaultPort?: number;
    deserializedFields?: URLStreamHandler;
    file?: string;
    host?: string;
    path?: string;
    port?: number;
    protocol?: string;
    query?: string;
    ref?: string;
    serializedHashCode?: number;
    userInfo?: string;
}
